_wandb:
    value:
        cli_version: 0.19.9
        m:
            - "1": Stochastic Gradient Descent_rmse
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch
              "6":
                - 3
              "7": []
            - "1": Mini-Batch Gradient Descent_rmse
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Batch Gradient Descent_rmse
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.11.9
        t:
            "1":
                - 5
                - 53
                - 55
            "2":
                - 5
                - 53
                - 55
            "3":
                - 3
                - 7
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.9
            "5": 0.19.9
            "8":
                - 3
                - 5
            "12": 0.19.9
            "13": windows-amd64
batch_size:
    value: null
eta0:
    value: 0.001
learning_rate:
    value: constant
max_iter:
    value: 1000
tol:
    value: 0.001
